bases:
  # - configs/oci/sft/2b_lora_mambav2_pre_f145_sft.yaml
  # - configs/oci/sft/2b_full_mambav2_pre_f145_sft.yaml
  - configs/oci/sft/5b_mambav2_pre_f145_sft.yaml
  - configs/oci/sft/5b_lora_mambav2_pre_f145_sft.yaml
  - configs/oci/sft/5b_full_mambav2_pre_f145_sft.yaml

common_configs:
  - configs/oci/inference/f145_infer.yaml