args:
  latent_channels: 16
  mode: inference
  batch_size: 1
  input_type: txt
  input_file: configs/test.txt
  # sampling_num_frames: 13  # Must be 13, 11 or 9
  sampling_fps: 8
  sampling_num_frames: 13  # Must be 13, 11 or 9
  # sampling_fps: 24
  bf16: True
  output_dir: output/inference
  force_inference: True
